# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1085757540f4f1cf9c4494da1660eba78ead2fbdf23ac1725b9d939c9883490e5bbfd1ef562ef026e3f66268d9bcc74e4010e83c7eb27a12b64030ab913f31f9

test:
  secret_key_base: db0ddbc799032e416438043af282e64832efa1d1c9dff5aa1b702409efb11684beabdd41c6d8424f9cce2efd8afd6e32e40efe99e3eeb981a7830afe07a4d51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
